name: autofix-on-pr

on:
  pull_request:
    branches: ["main"]   # PR 열리거나 업데이트될 때 자동 실행

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "autofix-on-pr-${{ github.event.pull_request.head.ref }}"
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          # 포크/동일 리포 모두 지원
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git (safe)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (never fail)
        run: |
          if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm i || true
          elif [ -f yarn.lock ]; then corepack enable && yarn i || true
          elif [ -f package-lock.json ]; then npm ci || npm i || true
          elif [ -f package.json ]; then npm i || true
          else echo "no deps"; fi

      - name: Auto-fix (Prettier/ESLint — safe)
        run: |
          npx --yes prettier . --write || true
          npx --yes eslint . --ext .js,.jsx,.ts,.tsx --fix || true

      - name: Auto-commit back to PR branch
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(autofix): apply automatic code fixes"
          branch: ${{ github.event.pull_request.head.ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Done (no changes)
        if: steps.commit.outputs.changes_detected != 'true'
        run: echo "No changes to commit."
