name: pr-smoke
on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Make a tiny change
        run: |
          echo "smoke $(date +%s)" >> .autofix_smoke.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

      - name: Open PR (fixed branch)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: bot/smoke           # 항상 같은 브랜치
          commit-message: "chore(smoke): touch"
          title: "chore(smoke): touch"
          body: "smoke test"
          delete-branch: true
